### ISSUE TITLE
With rake installed from rpm "gem test" reports << ERROR:  Couldn't find rake; rubygems-test will not work without it. Aborting. >>

### ISSUE THREAD

**Issue by shlomif** [rubygems/rubygems-test#10]
I have installed rake from rpm (on Mandriva Linux 2010.2 on an x86-64 computer) and gem test reports:

ERROR:  Couldn't find rake; rubygems-test will not work without it. Aborting.

Please fix it.

**Comment by erikh** [comment]
<pre>
rindolf | erikh: well, I installed Mandriva 2010.0 from the DVD and upgraded to Mandriva 2010.1/2010.2.
15:52:45         rindolf | erikh: and I think I installed some gems afterwards.
15:53:05         rindolf | erikh: but I don't remember the exact details. It was too long ago.
</pre>

**Comment by shlomif** [comment]
I should note that I've tried it on my x86-32 Mandriva Linux Cooker box (what will become Mandriva 2011.0) and it is working fine there and I was able to get "gem test kakuro_solver" to pass.

**Comment by shlomif** [comment]
OK, now after I did "gem update --system" and rebuilt the rubygems-test package, the problem has been solved and "gem test kakuro_solver" runs fine. It's possible it requires a bug fix in a recent version of rake or rubygem.

**Comment by erikh** [comment]
This is very good information; it means I need to bump the minimum rubygems version. I'll leave this open with the topic repurposed for that.

**Comment by erikh** [comment]
I've bumped the rubygems version in HEAD. This problem should be solved in 0.3.1.

**Comment by erikh** [comment]
pushed in 0.3.1
