### ISSUE TITLE
Gem::RakeNotFoundError installing tzinfo with Bundler

### ISSUE THREAD

**Issue by capoferro** [rubygems/rubygems-test#11]
Installing tzinfo (0.3.24) /home/josiah/.rvm/gems/ruby-1.9.2-p0/gems/rubygems-test-0.2.5/lib/rubygems/on_install_test.rb:13:in `rescue in block in <top (required)>': uninitialized constant Gem::RakeNotFoundError (NameError)
       from /home/josiah/.rvm/gems/ruby-1.9.2-p0/gems/rubygems-test-0.2.5/lib/rubygems/on_install_test.rb:11:in`block in <top (required)>'
       from /home/josiah/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/rubygems/installer.rb:216:in `call'
       from /home/josiah/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/rubygems/installer.rb:216:in`block in install'
       from /home/josiah/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/rubygems/installer.rb:215:in `each'
       from /home/josiah/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/rubygems/installer.rb:215:in`install'
       from /home/josiah/.rvm/gems/ruby-1.9.2-p0/gems/bundler-1.0.7/lib/bundler/source.rb:95:in `install'
       from /home/josiah/.rvm/gems/ruby-1.9.2-p0/gems/bundler-1.0.7/lib/bundler/installer.rb:55:in`block in run'
       from /home/josiah/.rvm/gems/ruby-1.9.2-p0/gems/bundler-1.0.7/lib/bundler/spec_set.rb:12:in `block in each'
       from /home/josiah/.rvm/gems/ruby-1.9.2-p0/gems/bundler-1.0.7/lib/bundler/spec_set.rb:12:in`each'
       from /home/josiah/.rvm/gems/ruby-1.9.2-p0/gems/bundler-1.0.7/lib/bundler/spec_set.rb:12:in `each'
       from /home/josiah/.rvm/gems/ruby-1.9.2-p0/gems/bundler-1.0.7/lib/bundler/installer.rb:44:in`run'
       from /home/josiah/.rvm/gems/ruby-1.9.2-p0/gems/bundler-1.0.7/lib/bundler/installer.rb:8:in `install'
       from /home/josiah/.rvm/gems/ruby-1.9.2-p0/gems/bundler-1.0.7/lib/bundler/cli.rb:225:in`install'
       from /home/

**Comment by erikh** [comment]
Curious, do you get this when you install gems without bundler?

**Comment by erikh** [comment]
Can you test with the latest HEAD? I think I fixed this.

**Comment by erikh** [comment]
Gonna close this, I think it was fixed in 0.3.0
