### ISSUE TITLE
Output looks too much like a backtrace.

### ISSUE THREAD

**Issue by postmodern** [rubygems/rubygems-test#16]
After successfully uploading test results, the output from `gem test` looks a little too much like an indented output. Three should be more spacing, ANSI coloring or a big message denoting everything passed.
### Looks like a backtrace:

```
Finished in 2.99 seconds
11 examples, 0 failures
/home/hal/.rvm/rubies/ruby-1.9.2-p136/bin/ruby -S rspec ./spec/dictionary_spec.rb ./spec/hunspell_spec.rbUpload these results? [Yn]  Y
Test results posted successfully! 
    http://gem-testers.org/gems/ffi-hunspell/v/0.2.2/test_results/93
```

**Comment by erikh** [comment]
What do you think of putting a couple of newlines in there instead and a "results url: " heading? The idea there was to make it stand out, but perhaps there is a better way.

**Comment by postmodern** [comment]
That would work. Also maybe adding an 80 column separator:

```
********************************************************************************
```

Whenever I see an indented path-like String, I immediately think backtrace.

**Comment by erikh** [comment]
I think I'm going to leave the stars out, but I've added some newlines and I think it makes it less compact and easier to read. It should be in HEAD within the hour.

**Comment by erikh** [comment]
Pushed with 0.3.1
