### ISSUE TITLE
Does not differentiate between prerelase versions.

### ISSUE THREAD

**Issue by postmodern** [rubygems/rubygems-test#17]
After `gem test`ing a pre-release of mine ([ronin-gen 1.0.0.rc1](http://rubygems.org/gems/ronin-gen/versions/1.0.0.rc1)) I noticed it uploaded the results to http://gem-testers.org/gems/ronin-gen/v/1.0.0/test_results/96. These results should be separated from the future ronin-gen 1.0.0 stable release.

**Comment by erikh** [comment]
I had thought we had covered this but apparently we haven't. I'll put in a ticket at the gem-testers project to ensure this is being properly addressed there, too.

**Comment by erikh** [comment]
This should be fixed in 0.3.3. Can you test?

**Comment by postmodern** [comment]
Fixed!
