### ISSUE TITLE
mixed output still happening

### ISSUE THREAD

**Issue by erikh** [rubygems/rubygems-test#18]
the stdio issue is still here; stderr and stdout are still getting merged in funky ways.

maybe timestamping and resolving the conflicts that way would be a better idea (thanks Rick Hull)

**Comment by rickhull** [comment]
Particularly, starting with the 8th "ok"

http://gem-testers.org/gems/pry/v/0.4.6/test_results/115

**Comment by erikh** [comment]
Pretty sure this is DTRT now; thanks again for the idea rick!
