### ISSUE TITLE
Testing behind a proxy

### ISSUE THREAD

**Issue by capoferro** [rubygems/rubygems-test#24]
I am able to install gems, but posting test results times out:

<pre>
josiah@BOX-OF-DOOOM:~$ gem test rubygems-test
Installing test dependency hoe (>= 2.9.1)
Installing test dependency minitest (>= 2.0.2)
Fetching: minitest-2.0.2.gem (100%)
Gem 'minitest' (version 2.0.2) needs to opt-in for testing.

Locally available testing helps gems maintain high quality by
ensuring they work correctly on a wider array of platforms than the
original developer can access.

If you are the author: 
 * Add the file '.gemtest' to your spec.files
 * Ensure 'rake test' works and doesn't do system damage
 * Add your tests and Rakefile to your gem.

For more information, please see the rubygems-test README:
https://github.com/rubygems/rubygems-test/blob/master/README.txt
(in /home/josiah/.rvm/gems/ruby-1.9.2-p0/gems/hoe-2.9.1)

Loaded suite -e
Started
...F....
Finished in 0.544689 seconds.

  1) Failure:
test_possibly_better(TestHoe) [/home/josiah/.rvm/gems/ruby-1.9.2-p0/gems/hoe-2.9.1/test/test_hoe.rb:107]:
Expected ["test/test_hoe.rb", "test/test_hoe_gemcutter.rb"], not ["test/test_hoe_gemcutter.rb", "test/test_hoe.rb"].

8 tests, 52 assertions, 1 failures, 0 errors, 0 skips

Test run options: --seed 17188
home/josiah/.rvm/rubies/ruby-1.9.2-p0/bin/ruby -w -I../../minitest/dev/lib:lib:bin:test:. -e 'require "rubygems"; require "tes
t/unit"; require "test/test_hoe_gemcutter.rb"; require "test/test_hoe.rb"' -- rake aborted!                                  
Command failed with status (1): [/home/josiah/.rvm/rubies/ruby-1.9.2-p0/bin...]
/home/josiah/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/rake.rb:993:in `block in sh'
/home/josiah/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/rake.rb:1008:in `call'
/home/josiah/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/rake.rb:1008:in `sh'
/home/josiah/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/rake.rb:1092:in `sh'
/home/josiah/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/rake.rb:1027:in `ruby'
/home/josiah/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/rake.rb:1092:in `ruby'
/home/josiah/.rvm/gems/ruby-1.9.2-p0/gems/hoe-2.9.1/lib/hoe/test.rb:74:in `block in define_test_tasks'
/home/josiah/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/rake.rb:634:in `call'
/home/josiah/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/rake.rb:634:in `block in execute'
/home/josiah/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/rake.rb:629:in `each'
/home/josiah/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/rake.rb:629:in `execute'
/home/josiah/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/rake.rb:595:in `block in invoke_with_call_chain'
/home/josiah/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/monitor.rb:201:in `mon_synchronize'
/home/josiah/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/rake.rb:588:in `invoke_with_call_chain'
/home/josiah/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/rake.rb:581:in `invoke'
/home/josiah/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/rake.rb:2041:in `invoke_task'
/home/josiah/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/rake.rb:2019:in `block (2 levels) in top_level'
/home/josiah/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/rake.rb:2019:in `each'
/home/josiah/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/rake.rb:2019:in `block in top_level'
/home/josiah/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/rake.rb:2058:in `standard_exception_handling'
/home/josiah/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/rake.rb:2013:in `top_level'
/home/josiah/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/rake.rb:1992:in `run'
/home/josiah/.rvm/gems/ruby-1.9.2-p0/gems/rake-0.8.7/bin/rake:31:in `<main>'
No route to host - connect(2)
ERROR:  Tests did not pass. Examine the output and report it to the author!
Testing hoe (2.9.1) failed. Uninstall? [yN]  n
(in /home/josiah/.rvm/gems/ruby-1.9.2-p0/gems/rubygems-test-0.3.5)

Loaded suite -e
Started
..

Successfully uninstalled test-gem-0.0.0

.

Successfully uninstalled test-gem-0.0.0
/home/josiah/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/site_ruby/1.9.1/rubygems/specification.rb:726:in `to_yaml': YAML.quick_emit is
 deprecatedERROR:  Couldn't find rakefile -- this gem cannot be tested. Aborting.                                            
Successfully uninstalled test-gem-0.0.0
.
Successfully uninstalled test-gem-0.0.0
..
Finished in 2.911829 seconds.

6 tests, 12 assertions, 0 failures, 0 errors, 0 skips

Test run options: --seed 38624
Connection timed out - connect(2)</pre>

**Comment by erikh** [comment]
I don't have a proxy available; can you test the proxy-support branch in your environment?

**Comment by erikh** [comment]
looking good, next release ho!!!!
