### ISSUE TITLE
gemtest ignored by rubinius

### ISSUE THREAD

**Issue by banister** [rubygems/rubygems-test#28]
I have the latest version of rubygems and the latest version of rubygems-test installed, i also have a .gemtest file in my gem -- all other platforms (MRI/YARV) respect it and perform the test but rubinius seems to say i need to 'opt in'
john@littleblood ~ $ gem test pry
Gem 'pry' (version >= 0) needs to opt-in for testing.

rubinius version: rubinius 1.0.1 (1.8.7 release 2010-06-03 JI) [i686-pc-linux-gnu]

**Comment by erikh** [comment]
can you verify this is solved on your rubinius installation with the latest version?

**Comment by erikh** [comment]
I think this was resolved a while back.
