### ISSUE TITLE
Error installing gems after installing rubygems-test

### ISSUE THREAD

**Issue by rosstimson** [rubygems/rubygems-test#31]
As soon as I install the latest rubygems-test (0.4.0) gem I cannot install any gems afterwards.  I get the following error:

ERROR:  Could not find gem <GEMNAME> (xxxx)
ERROR:  Could not find a valid gem '' () in any repository
ERROR:  While executing gem ... (NoMethodError)
    undefined method `downcase' for nil:NilClass

I had originally thought this was an unrelated issue with my environment so wiped out my local gem source_cache and everything seemed fine.  Installations of gems only stopped working when I reinstalled rubygems-test, uninstalling fixes the issue.

My environment is:
Mac OS X 10.6.7
Ruby 1.9.2p180 (under RVM)
Rubygems 1.7.2

My .gemrc has these options for rubygems-test:

test_options:
  auto_test_on_install: true
  install_development_dependencies: true
  upload_results: true
  force_install: true # set if you want to install gems even if they fail tests.
  force_uninstall_on_failure: false

**Comment by erikh** [comment]
Knowing what gems you're trying to install would really help expose the issues.

**Comment by rosstimson** [comment]
Sorry, first time round it was haml, sass, and compass.  They were all recently updated so I thought it was specific to them however I blitzed entire cache and started over.  I was just reinstalling some of the gems I had before wiping everything when the issue popped up again, it seemed to be all gems.

Just tested a little by removing some random gems (slim, unicorn, nanoc, compass-susy-plugin), next reinstalled rubygems-test and tried reinstalling the afore mentioned gems; no joy - same error on all of them and all successfully install again once rubygems-test is removed.

**Comment by erikh** [comment]
Ok, thanks. I'll try to address this tomorrow evening. I suspect it's the combination of force_install and auto_test...

**Comment by erikh** [comment]
I've released 0.4.1; do you mind testing this gem out and seeing if it resolves your issue? You may need to uninstall any versions of rubygems-test you have installed first.

**Comment by rosstimson** [comment]
Spot on this seems to have done the trick, tested with same gems as before without any problems. Thanks.
